language: cpp
matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CXX=g++-7"
before_install:
  - eval "${MATRIX_EVAL}"
script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - ctest --verbose
  - make install