name: Build All
on:
  push:
    branches:
      - master

jobs:
  build:
    name: build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: configure
        run: |
          mkdir build
          cd build
          cmake ..
      - name: build
<<<<<<< HEAD
        run: |
          cd build
          cmake --build .
      - name: test
        run: |
          cd build
          ctest --verbose
      - name: install
        run: |
          cd build
          make install
=======
        run: cmake --build .
      - name: test
        run: ctest --verbose
      - name: install
        run: make install
>>>>>>> afa91044e3d540f470c97780c01ac37d1f2682b6

